Switch to pyproject.toml
Starting with [PEP 621](https://peps.python.org/pep-0621/), the Python
community selected pyproject.toml as a standard way of specifying
project metadata. Setuptools has adopted this standard and will use the
information contained in this file as an input in the build process.

Dropped the `platforms` key, it caused the following error on `python -m
build`:

```
ValueError: invalid pyproject.toml config: `project`.
configuration error: `project` must not contain {'platforms'} properties
```